name: Code Style

on: [push, pull_request]

jobs:
  build:
    name: "Lint Code Base"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml
          FLAKE8_VERSION=$(python version_from_lock.py flake8)
          BLACK_VERSION=$(python version_from_lock.py black)
          pip install "flake8==${FLAKE8_VERSION}" "black==${BLACK_VERSION}"
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
      - name: Check with black
        run: |
          black . --check --diff
      - name: Run GitHub super-linter
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_DOCKER: true
          VALIDATE_GO: true
          VALIDATE_ENV: true
